destination: x_cloud_output/pdf
url: "http://127.0.0.1:4010"
baseurl: "/cloud-gs-pdf"
port: 4010
output: pdf
product: cloud_apps
print_title: Weebly Cloud
print_subtitle: Create Custom Apps
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true